import * as THREE from 'three';

// Per-scene configuration consumed by the world in main.js.
// Each block fully describes sky, lighting, clouds, particles, fog and post FX
// so switching scenes is a single declarative apply().
const dir = (x, y, z) => new THREE.Vector3(x, y, z).normalize();

export const SCENE_CONFIG = {
  'clear-day': {
    sky: {
      top: '#1a57b8',
      horizon: '#86b6e0',
      bottom: '#0d2244',
      glow: '#ffe7ad',
      glowStrength: 0.9,
      glowSharp: 300,
      lightDir: dir(0.34, 0.42, -1),
    },
    ambient: 0.9,
    sun: true,
    moon: false,
    stars: false,
    clouds: { coverage: 0.3, opacity: 0.3, color: '#eef3fa', shadow: '#bcd2ea' },
    rain: 0,
    snow: 0,
    ground: 0,
    lightning: false,
    fog: { color: '#9cc2e6', density: 0.0016 },
    bloom: { strength: 0.7, radius: 0.6, threshold: 0.9 },
  },

  'clear-night': {
    sky: {
      top: '#040814',
      horizon: '#16243f',
      bottom: '#02040a',
      glow: '#bcd0ff',
      glowStrength: 0.7,
      glowSharp: 320,
      lightDir: dir(-0.32, 0.42, -1),
    },
    ambient: 0.18,
    sun: false,
    moon: true,
    stars: true,
    clouds: { coverage: 0.18, opacity: 0.15, color: '#2a3a57', shadow: '#0c1424' },
    rain: 0,
    snow: 0,
    ground: 0,
    lightning: false,
    fog: { color: '#0a1224', density: 0.0016 },
    // high threshold + low strength so only the very brightest specular spots
    // bloom: keeps the cratered moon disc crisp and round instead of a white
    // blob, while bright stars still glint.
    bloom: { strength: 0.35, radius: 0.35, threshold: 0.82 },
  },

  clouds: {
    sky: {
      top: '#52697f',
      horizon: '#90a1b4',
      bottom: '#39465a',
      glow: '#b9c5d4',
      glowStrength: 0.18,
      glowSharp: 120,
      lightDir: dir(0.2, 0.5, -1),
    },
    ambient: 0.6,
    sun: false,
    moon: false,
    stars: false,
    clouds: { coverage: 0.72, opacity: 0.92, color: '#d2dbe6', shadow: '#74859a' },
    rain: 0,
    snow: 0,
    ground: 0,
    lightning: false,
    fog: { color: '#8fa0b2', density: 0.0026 },
    bloom: { strength: 0.28, radius: 0.5, threshold: 0.88 },
  },

  rain: {
    sky: {
      top: '#3b485c',
      horizon: '#6e7d8f',
      bottom: '#252e3c',
      glow: '#9fb0c4',
      glowStrength: 0.2,
      glowSharp: 90,
      lightDir: dir(0.1, 0.6, -1),
    },
    ambient: 0.45,
    sun: false,
    moon: false,
    stars: false,
    clouds: { coverage: 0.82, opacity: 0.97, color: '#c4cdd9', shadow: '#525f72' },
    rain: 0.95,
    rainOpts: { color: '#cfe0ff', wind: 7, fall: 60 },
    snow: 0,
    ground: 0.95,
    groundColor: '#dcebff',
    lightning: false,
    fog: { color: '#6b7888', density: 0.0036 },
    bloom: { strength: 0.45, radius: 0.6, threshold: 0.7 },
  },

  snow: {
    sky: {
      top: '#6d7d93',
      horizon: '#aeb9c8',
      bottom: '#54627a',
      glow: '#d3dbe6',
      glowStrength: 0.2,
      glowSharp: 100,
      lightDir: dir(0.0, 0.6, -1),
    },
    ambient: 0.75,
    sun: false,
    moon: false,
    stars: false,
    clouds: { coverage: 0.58, opacity: 0.65, color: '#dde4ec', shadow: '#94a3b8' },
    rain: 0,
    snow: 1.0,
    ground: 0,
    lightning: false,
    fog: { color: '#bcc6d4', density: 0.0042 },
    bloom: { strength: 0.3, radius: 0.6, threshold: 0.85 },
  },

  thunderstorm: {
    sky: {
      top: '#161c2a',
      horizon: '#363f52',
      bottom: '#0c1019',
      glow: '#6577a0',
      glowStrength: 0.15,
      glowSharp: 80,
      lightDir: dir(0.0, 0.6, -1),
    },
    ambient: 0.28,
    sun: false,
    moon: false,
    stars: false,
    clouds: { coverage: 0.9, opacity: 1.0, color: '#5a6678', shadow: '#1b2230' },
    rain: 1.0,
    rainOpts: { color: '#b9cdf0', wind: 11, fall: 75 },
    snow: 0,
    ground: 1.0,
    groundColor: '#c8d8f4',
    lightning: true,
    fog: { color: '#2b3344', density: 0.0044 },
    bloom: { strength: 0.7, radius: 0.7, threshold: 0.55 },
  },

  fog: {
    sky: {
      top: '#8a939e',
      horizon: '#b0b7c0',
      bottom: '#737b86',
      glow: '#c4cad2',
      glowStrength: 0.15,
      glowSharp: 70,
      lightDir: dir(0.0, 0.55, -1),
    },
    ambient: 0.7,
    sun: false,
    moon: false,
    stars: false,
    clouds: { coverage: 0.45, opacity: 0.4, color: '#cfd5dc', shadow: '#9aa1ab' },
    rain: 0,
    snow: 0,
    ground: 0,
    lightning: false,
    fog: { color: '#b6bcc4', density: 0.014 },
    bloom: { strength: 0.25, radius: 0.5, threshold: 0.85 },
  },
};
